version: "3.8"

services:
  database:
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_USER=devOCVUser
      - POSTGRES_PASSWORD=6UN6bid_rDHKGTs
      - POSTGRES_DB=onecv-asgt-db
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data 
  backend:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - database
    
volumes:
  db: